# Generated by Django 4.1.7 on 2023-08-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(default=None, max_length=10)),
                ('course_title', models.CharField(default=None, max_length=100)),
                ('batch', models.CharField(choices=[('', 'select batch'), ('2019-2023', 'Y19-batch'), ('2020-2024', 'Y20-batch'), ('2021-2025', 'Y21-batch'), ('2022-2026', 'Y22-batch'), ('2023-2027', 'Y23-batch')], default=None, max_length=10)),
                ('year', models.CharField(choices=[('', 'select year'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], default=None, max_length=10)),
                ('semester', models.CharField(choices=[('', 'select'), ('odd', 'Odd'), ('even', 'Even'), ('summer', 'Summerterm')], default=None, max_length=10)),
                ('credits', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('L', models.IntegerField(default=None)),
                ('T', models.IntegerField(default=None)),
                ('P', models.IntegerField(default=None)),
                ('S', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField(default=None, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(choices=[('', 'select'), ('male', 'Male'), ('female', 'Female')], default='prefer_not_to_say', max_length=20)),
                ('department', models.CharField(choices=[('Cse', 'CSE'), ('Csit', 'CSIT'), ('Aids', 'AIDS'), ('Ece', 'ECE'), ('Eee', 'EEE'), ('BBA', 'BBA'), ('Mechanical', 'Mechanical'), ('Biotechnology', 'Biotechnology'), ('Civil', 'Civil'), ('Mba', 'MBA'), ('B.arch', 'B.Arch')], default=None, max_length=50)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer')], default=None, max_length=50)),
                ('qualification', models.CharField(choices=[('PhD', 'PhD'), ('Masters', "Master's"), ('Msc', 'M.Sc'), ('Bsc', 'B.Sc'), ('Bed', 'B.Ed')], default=None, max_length=20)),
                ('contact', models.BigIntegerField(default=None, unique=True)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=None, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('gender', models.CharField(choices=[('', 'select'), ('male', 'Male'), ('female', 'Female')], default='prefer_not_to_say', max_length=20)),
                ('department', models.CharField(choices=[('Cse', 'CSE'), ('Csit', 'CSIT'), ('Aids', 'AIDS'), ('Ece', 'ECE'), ('Eee', 'EEE'), ('BBA', 'BBA'), ('Mechanical', 'Mechanical'), ('Biotechnology', 'Biotechnology'), ('Civil', 'Civil'), ('Mba', 'MBA'), ('B.arch', 'B.Arch')], default=None, max_length=50)),
                ('batch', models.CharField(choices=[('', 'select batch'), ('2019-2023', 'Y19-batch'), ('2020-2024', 'Y20-batch'), ('2021-2025', 'Y21-batch'), ('2022-2026', 'Y22-batch'), ('2023-2027', 'Y23-batch')], default=None, max_length=10)),
                ('present_year', models.CharField(choices=[('', 'select year'), ('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], default=None, max_length=10)),
                ('semester', models.CharField(choices=[('', 'select'), ('odd', 'Odd'), ('even', 'Even'), ('summer', 'Summerterm')], default=None, max_length=10)),
                ('contact', models.BigIntegerField(default=None, unique=True)),
            ],
        ),
    ]
