# Generated by Django 4.1.7 on 2023-08-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0005_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
    ]
